"Getting started" was not smooth for macOS
I had some troubles while following the steps, with these changes, it should be smooth.

Here are the stuff I wrote down while I was trying to install it, please check if I made a mistake.

Installing Komodo Daemon on macOS, following "Getting Started" in the GitHub repository.

- In "Dependencies" section, I had to change "sudo apt-get install" to "brew install"

- Then got this error:
    Error: No available formula with the name "build-essential" 
    ==> Searching for a previously deleted formula (in the last month)...
    Warning: homebrew/core is shallow clone. To get complete history run:
    git -C "$(brew --repo homebrew/core)" fetch --unshallow

    Error: No previously deleted formula found.
    ==> Searching for similarly named formulae...
    Error: No similarly named formulae found.
    ==> Searching taps...
    ==> Searching taps on GitHub...
    Warning: Error searching on GitHub: GitHub Bad credentials:The GitHub credentials in the macOS keychain may be invalid.
    Clear them with:
    printf "protocol=https\nhost=github.com\n" | git credential-osxkeychain erase
    Or create a personal access token:
    https://github.com/settings/tokens/new?scopes=gist,public_repo&description=Homebrew
    echo 'export HOMEBREW_GITHUB_API_TOKEN=your_token_here' >> ~/.bash_profile

    Error: No formulae found in taps.

- I ran "xcode-select --install" to make sure I have everything.

- Realised I didn't need to go through the "Dependencies" section in macOS. (Turns out, xcode does not install them all so some of them will be missing after this)

- Continued in Build Komodo -> OSX, 

- "brew update && brew install gcc@6" resulted in an error, Error: The following directories are not writable by your user: /usr/local/share/man/man7

- I had to run "sudo chown -R $(whoami) /usr/local/share/man/man7"

- Then I ran "brew update && brew install gcc@6" again. It went successfully.

- "./zcutil/fetch-params.sh" resulted with error:
    ./zcutil/fetch-params.sh: line 112: flock: command not found
    Only one instance of fetch-params.sh can be run at a time.

- Removed "function lock()" block and the call of it.

- Another error appeared when I ran the script again:
    Failed to fetch the Zcash zkSNARK parameters!
    Try installing one of the following programs and make sure you're online:

    * ipfs
    * wget

- Ran "brew install ipfs", "ipfs init", "ipfs daemon".

- Ran "./zcutil/fetch-params.sh" again. Started downloading sprout-proving-key.dl (860 MB), but download speed is incredibly slow.

- Ran "./zcutil/build-mac.sh", resulted with error:
    cd /Users/naezith/Documents/komodo/depends/work/build/x86_64-apple-darwin18.0.0/libevent/2.1.8-53dd794d1f9;   ./autogen.sh
    ./autogen.sh: line 18: aclocal: command not found
    make: *** [/Users/naezith/Documents/komodo/depends/work/build/x86_64-apple-darwin18.0.0/libevent/2.1.8-53dd794d1f9/.stamp_preprocessed] Error 127

- Ran "brew install automake"

- Ran "./zcutil/build-mac.sh", resulted with error again:
    cd /Users/naezith/Documents/komodo/depends/work/build/x86_64-apple-darwin18.0.0/libevent/2.1.8-53dd794d1f9;   ./autogen.sh
    autoreconf: Entering directory `.'
    autoreconf: configure.ac: not using Gettext
    autoreconf: running: aclocal --force -I m4
    autoreconf: configure.ac: tracing
    autoreconf: configure.ac: not using Libtool
    autoreconf: running: /usr/local/Cellar/autoconf/2.69/bin/autoconf --force
    configure.ac:129: error: possibly undefined macro: AC_PROG_LIBTOOL
        If this token and others are legitimate, please use m4_pattern_allow.
        See the Autoconf documentation.
    autoreconf: /usr/local/Cellar/autoconf/2.69/bin/autoconf failed with exit status: 1
    make: *** [/Users/naezith/Documents/komodo/depends/work/build/x86_64-apple-darwin18.0.0/libevent/2.1.8-53dd794d1f9/.stamp_preprocessed] Error 1

- Seems like I don't have all the dependencies on top, installed them with "brew install curl wget unzip libtool m4 pkg-config"

- Ran "./zcutil/build-mac.sh" again, took so long.

- Created komodo.conf file.

- It was not clear that "komodod" file is inside "src" folder.

- Started the server with: ./komodod -ac_name=naechain -ac_supply=100000 -bind=127.0.0.1 & 

- After all these, I realized that there is README-mac.md but it was too late.